root: ../../../
configDir: perl-web-kb/config
cgiDir: perl-web-kb/cgi-bin
htmlDir: perl-web-kb/html
libDir: perl-web-kb/cgi-bin/lib
logDir: perl-web-kb/log
tmplDir: perl-web-kb/tmpl
dbDir: perl-web-kb/db/data
db_odbc_driver: 'dbi:SQLite:'
db_odbc_dbname: kb_1.db
db_odbc_user:
db_odbc_pass:
htmlcgi: ../cgi-bin
cssDir: perl-web-kb/html/css
uploadDir: perl-web-kb/uploads
uploadLinkOffset: ../../../../perl-web-kb/uploads
