root: ../../../
configDir: kb/config
cgiDir: kb/cgi-bin
htmlDir: kb/html
libDir: kb/cgi-bin/lib
logDir: kb/log
tmplDir: kb/tmpl
dbDir: kb/db/data
db_odbc_driver: 'dbi:SQLite:'
db_odbc_dbname: kb_1.db
db_odbc_user:
db_odbc_pass:
htmlcgi: ../cgi-bin
